const mongoose =require("mongoose");
const mongoosePaginate = require("mongoose-paginate-v2");

const FilmModel = new mongoose.Schema({
  imdb_id:{
    type:String,
    required:true
  },
  comments:{
    type:[{
      userId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'User'
      },
      comment:String
    }],
    default:[]
  },
  rates:{
    type:[{
      userId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'User'
      },
      rate:Number
    }],
    default:[]
  },
  title:{
    type:String,
    default:''
  },
  poster:{
    type:String,
    default:''
  },
  isSerial:{
    type:Boolean,
    default:false
  },
  isFavorites:{
    type:[{
      userId:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:'User'
      },
      isFavorite:Boolean
    }],
    default:[]
  },
  userId:{
    type:[mongoose.Schema.Types.ObjectId],
    required:true,
    ref:'User'
  },
},{
  timestamps:true
})
FilmModel.plugin(mongoosePaginate);
// export default mongoose.model('Film',FilmModel)
module.exports=mongoose.model('Film',FilmModel)
